# Change overlap value

Now, it is possible change the samples overlap for model input. Overlap is the number of sequential samples shared between the inputs. As example:

```python
input_0 = [0, 1, 2, 3, 4]
input_1 = [1, 2, 3, 4, 5]
input_2 = [4, 5, 6, 7, 8]
```
There is 4 samples overlaped between ```input_0``` and ```input_1```. 1, 2, 3, and 4 are these values samples.
There is 2 samples overlaped between ```input_1``` and ```input_2```. 4, and 5 are these values samples.
And there is 1 sample overlaped between ```input_0``` and ```input_2```. The 4 are this value sample.

As model input:

In [1]:
import sys

sys.path.append("../src")

import data_manner
import configs_manner
import numpy as np

repo = "p971074907"
path = "brl:rn"
feature = "date:newDeaths:newCases:"
begin = "2020-05-01"
end = "2022-07-01"

# creating a data constructor object
data_constructor = data_manner.DataConstructor()
collected_data = data_constructor.collect_dataframe(path, repo, feature, begin, end)
# window size = 7
data_train = data_constructor.build_train(collected_data)
print(data_train.x[0])
print("\n")
print(data_train.x[1])

[[ 0.42857143 12.85714286]
 [ 0.42857143 12.85714286]
 [ 0.42857143 12.85714286]
 [ 0.42857143 12.85714286]
 [ 0.42857143 12.85714286]
 [ 0.42857143 12.85714286]
 [ 0.42857143 12.85714286]]


[[ 0.42857143 12.85714286]
 [ 0.42857143 12.85714286]
 [ 0.42857143 12.85714286]
 [ 0.42857143 12.85714286]
 [ 0.42857143 12.85714286]
 [ 0.42857143 12.85714286]
 [ 0.42857143  1.71428571]]


The default overlap value is the window input size -1. You can set this value in the ```configure.json``` file. The value is restrict by maximum from ```input_windows_size - 1``` to the minimum 1 (or ```(input_windows_size - 1)  >= 1 ```). 

As said, you can set up this value directly in the ```configure.json``` file or you can change this value using the ```configs_manner``` module function ```add_variable_to_globals()```.

In [2]:
# change overlap to 4 samples
configs_manner.add_variable_to_globals('overlap_in_samples', 4)

data_train = data_constructor.build_train(collected_data)
print(data_train.x[0])
print("\n")
print(data_train.x[1])

[[ 0.42857143 12.85714286]
 [ 0.42857143 12.85714286]
 [ 0.42857143 12.85714286]
 [ 0.42857143 12.85714286]
 [ 0.42857143 12.85714286]
 [ 0.42857143 12.85714286]
 [ 0.42857143 12.85714286]]


[[ 0.42857143 12.85714286]
 [ 0.42857143 12.85714286]
 [ 0.42857143 12.85714286]
 [ 0.42857143 12.85714286]
 [ 0.42857143  1.71428571]
 [ 0.71428571 -1.14285714]
 [ 1.14285714 -2.71428571]]


As showed, the number of sequential shared samples as the first 4 values. If you try to change the value to a ivalid value, a error message was trigged.

In [3]:
# change overlap to an invalid value 10 samples (that is bigger than the window size 7)
configs_manner.add_variable_to_globals('overlap_in_samples', 10)

data_train = data_constructor.build_train(collected_data)
print(data_train.x[0])
print("\n")
print(data_train.x[1])

AssertionError: invalid overlap value

Another example of a invalid number.

In [4]:
# change overlap to an invalid value 7 samples (that is equal to the window size 7)
configs_manner.add_variable_to_globals('overlap_in_samples', 7)

data_train = data_constructor.build_train(collected_data)
print(data_train.x[0])
print("\n")
print(data_train.x[1])

AssertionError: invalid overlap value